
export async function getServerSideProps() {
  return {
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
}

export default function Index() {
  return null;
}


// import Head from "next/head";
// import { Fredoka } from "next/font/google";

// const fredoka = Fredoka({
//   variable: "--fonte-padrao",
//   subsets: ["latin"],
// });


// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div
//         className={``}
//       >

//       </div>
//     </>
//   );
// }
